"""drop unique constraint on wind_fetch_audit.data_source_version

Revision ID: 297272847a56
Revises: 98d8d7c8349a
Create Date: 2026-05-11 08:23:55

`data_source_version` is a **grouping** key, not a primary key. One
scheduled fetch run (`run_daily_fetch`) produces many `wind_fetch_audit`
rows — one per Wind tool call / ETF in the pool — and they all share
the same version token. The original `unique=True` constraint was
incorrect: it broke the very first multi-ETF run with a `UNIQUE
constraint failed` error.

This migration drops the UNIQUE-ness while keeping the index (lookups
for "show me every row from this version" must stay fast).

The autogenerated `BigInteger().with_variant(Integer, "sqlite")`
`alter_column` lines are no-ops at the SQL level; trimmed out.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "297272847a56"
down_revision: Union[str, None] = "98d8d7c8349a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite needs batch_alter_table for index changes on existing rows.
    with op.batch_alter_table("wind_fetch_audit") as batch_op:
        batch_op.drop_index("ix_wind_fetch_audit_data_source_version")
        batch_op.create_index(
            "ix_wind_fetch_audit_data_source_version",
            ["data_source_version"],
            unique=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("wind_fetch_audit") as batch_op:
        batch_op.drop_index("ix_wind_fetch_audit_data_source_version")
        batch_op.create_index(
            "ix_wind_fetch_audit_data_source_version",
            ["data_source_version"],
            unique=True,
        )
