"""add missing_reason to etf_daily_snapshot

Revision ID: 98d8d7c8349a
Revises: c026273dc95d
Create Date: 2026-05-11 06:03:00

Linda msg=5520b860 + Keira msg=33f426b9 hard line: distinguish *why* a
numeric field is null so the frontend can show "缺失原因" instead of a
generic "无数据". Adds a nullable enum column to `etf_daily_snapshot`
with seven seed values — the three Phase 1 ones (`invalid_value`,
`not_returned`, `not_applicable`) plus four extra ops categories from
Linda v3 SSOT field dictionary so future parser branches don't need
another migration just to add a new reason code.

NULL when `shares_status="VALID"`; the parser writes the matching
reason for the other three enum values.

The autogenerated `alter_column` lines for every existing
`BigInteger`/`BigInteger().with_variant(Integer, "sqlite")` column
were no-ops at SQL level (the variant is a SQLAlchemy-side type hint;
SQLite already stored those columns as `INTEGER PRIMARY KEY
AUTOINCREMENT`). Trimmed out so the migration diff is solely the
`missing_reason` addition.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "98d8d7c8349a"
down_revision: Union[str, None] = "c026273dc95d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_MISSING_REASON_ENUM = sa.Enum(
    "invalid_value",
    "not_returned",
    "not_applicable",
    "non_trading_day",
    "suspended_or_abnormal",
    "wind_field_uncovered",
    "parse_error",
    name="missing_reason_enum",
)


def upgrade() -> None:
    # SQLite needs `batch_alter_table` to add a column whose CHECK
    # constraint (what an Enum lowers to) references the table itself.
    # The recipe is portable — Postgres also accepts it.
    with op.batch_alter_table("etf_daily_snapshot") as batch_op:
        batch_op.add_column(
            sa.Column("missing_reason", _MISSING_REASON_ENUM, nullable=True)
        )


def downgrade() -> None:
    with op.batch_alter_table("etf_daily_snapshot") as batch_op:
        batch_op.drop_column("missing_reason")
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        _MISSING_REASON_ENUM.drop(bind, checkfirst=True)
