"""initial schema (wind audit + derived + encrypted config)

Revision ID: c026273dc95d
Revises: 
Create Date: 2026-05-11 04:47:24.725517

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c026273dc95d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'rotate_master_key', 'seeded_from_env', 'test_connection', name='config_action_enum'), nullable=False),
    sa.Column('config_type', sa.Enum('secret', 'runtime', name='config_type_enum'), nullable=False),
    sa.Column('config_name', sa.String(length=120), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_ip', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_audit_log_config_name'), 'config_audit_log', ['config_name'], unique=False)
    op.create_index(op.f('ix_config_audit_log_timestamp'), 'config_audit_log', ['timestamp'], unique=False)
    op.create_table('daily_report_provenance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('markdown_path', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source_versions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('runtime_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('secret_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('algorithm_version', sa.Integer(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wind_fetch_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('wind_tool_name', sa.String(length=120), nullable=False),
    sa.Column('wind_request_payload', sa.String(), nullable=False),
    sa.Column('wind_raw_response', sa.String(), nullable=False),
    sa.Column('wind_fetch_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_source_version', sa.String(length=64), nullable=False),
    sa.Column('derived_record_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_fetch_audit_data_source_version'), 'wind_fetch_audit', ['data_source_version'], unique=True)
    op.create_index('ix_wind_fetch_audit_tool_date', 'wind_fetch_audit', ['wind_tool_name', 'trade_date'], unique=False)
    op.create_index(op.f('ix_wind_fetch_audit_trade_date'), 'wind_fetch_audit', ['trade_date'], unique=False)
    op.create_table('etf_daily_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wind_fetch_audit_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_version', sa.String(length=64), nullable=False),
    sa.Column('windcode', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('fund_size_yuan', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('cumulative_nav', sa.Float(), nullable=True),
    sa.Column('change_range', sa.Float(), nullable=True),
    sa.Column('iopv', sa.Float(), nullable=True),
    sa.Column('forward_discount', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('shares_status', sa.Enum('VALID', 'INVALID', 'MISSING', 'NOT_APPLICABLE', name='shares_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['wind_fetch_audit_id'], ['wind_fetch_audit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('windcode', 'trade_date', 'data_source_version', name='uq_etf_daily_code_date_version')
    )
    op.create_index(op.f('ix_etf_daily_snapshot_data_source_version'), 'etf_daily_snapshot', ['data_source_version'], unique=False)
    op.create_index(op.f('ix_etf_daily_snapshot_trade_date'), 'etf_daily_snapshot', ['trade_date'], unique=False)
    op.create_index(op.f('ix_etf_daily_snapshot_wind_fetch_audit_id'), 'etf_daily_snapshot', ['wind_fetch_audit_id'], unique=False)
    op.create_index(op.f('ix_etf_daily_snapshot_windcode'), 'etf_daily_snapshot', ['windcode'], unique=False)
    op.create_table('fund_company_aggregate',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wind_fetch_audit_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source_version', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('aum_yuan', sa.Float(), nullable=True),
    sa.Column('fund_count', sa.Integer(), nullable=True),
    sa.Column('etf_aum_yuan', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['wind_fetch_audit_id'], ['wind_fetch_audit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'trade_date', 'data_source_version', name='uq_fund_company_date_version')
    )
    op.create_index(op.f('ix_fund_company_aggregate_company_name'), 'fund_company_aggregate', ['company_name'], unique=False)
    op.create_index(op.f('ix_fund_company_aggregate_data_source_version'), 'fund_company_aggregate', ['data_source_version'], unique=False)
    op.create_index(op.f('ix_fund_company_aggregate_trade_date'), 'fund_company_aggregate', ['trade_date'], unique=False)
    op.create_index(op.f('ix_fund_company_aggregate_wind_fetch_audit_id'), 'fund_company_aggregate', ['wind_fetch_audit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_company_aggregate_wind_fetch_audit_id'), table_name='fund_company_aggregate')
    op.drop_index(op.f('ix_fund_company_aggregate_trade_date'), table_name='fund_company_aggregate')
    op.drop_index(op.f('ix_fund_company_aggregate_data_source_version'), table_name='fund_company_aggregate')
    op.drop_index(op.f('ix_fund_company_aggregate_company_name'), table_name='fund_company_aggregate')
    op.drop_table('fund_company_aggregate')
    op.drop_index(op.f('ix_etf_daily_snapshot_windcode'), table_name='etf_daily_snapshot')
    op.drop_index(op.f('ix_etf_daily_snapshot_wind_fetch_audit_id'), table_name='etf_daily_snapshot')
    op.drop_index(op.f('ix_etf_daily_snapshot_trade_date'), table_name='etf_daily_snapshot')
    op.drop_index(op.f('ix_etf_daily_snapshot_data_source_version'), table_name='etf_daily_snapshot')
    op.drop_table('etf_daily_snapshot')
    op.drop_index(op.f('ix_wind_fetch_audit_trade_date'), table_name='wind_fetch_audit')
    op.drop_index('ix_wind_fetch_audit_tool_date', table_name='wind_fetch_audit')
    op.drop_index(op.f('ix_wind_fetch_audit_data_source_version'), table_name='wind_fetch_audit')
    op.drop_table('wind_fetch_audit')
    op.drop_table('secret_config')
    op.drop_table('runtime_config')
    op.drop_table('daily_report_provenance')
    op.drop_index(op.f('ix_config_audit_log_timestamp'), table_name='config_audit_log')
    op.drop_index(op.f('ix_config_audit_log_config_name'), table_name='config_audit_log')
    op.drop_table('config_audit_log')
    # ### end Alembic commands ###
